### PR TITLE
Add DLA

### PR DESCRIPTION
**Pull request by fjaviersanchez**
This pull request adds reads the skewers in one file and adds a new HDU flagging the pixels where we are able to add DLAs with a given bias (inversely proportional to the growth).

For now, it just flags the pixels. A results for a subset can be seen in the image below:

image

The yellow dots are the flagged pixels. In order to use it you would do `python --input-file INPUT --dla_bias 2.0 --output-file OUTPUT` if output is not specified it overwrites the input file adding the HDU in it. For now, there are no correlations between skewers.

### CODE REVIEW

**Comment by andreufont** [comment]
@fjaviersanchez - this looks great, thanks! 

There are two small things that we still need to do:
 - get the peculiar velocity in the cell where the DLA is, let's call it dz_dla. Add it to the redshift of the DLA, z_dla += dz_dla. It would be good to store both in the new HDU, one column with redshfit without RSD, and one with RSD, similar to what we do with the quasars.  
 - for each DLA at a given z (without the RSD), use the column density distribution f(N,z) to draw a random value for the column density N, between min_N and max_N. Store this as well in the new HDU.

With these two changes we are ready to go!

**Comment by fjaviersanchez** [comment]
So for the first part it would be just read the velocity of the skewer in that cell, right? And for the second part it would be to get a value for N, given the z of the DLA weighting by f(N,z)?

**Comment by andreufont** [comment]
Yes to both questions. 

I don't remember now what is stored in the "velocity skewers", though... is it dz_rsd? or something with units of velocity? In any case, it should be easy to get what we want (difference in redshift).

By the way, I just took a look at the code, and I'm a bit worried about the initialization of v_skw (the velocity skewer). I just did 

grep v_skw src/*.c

and noticed that the array v_skw gets memory allocated with malloc (in common.c) and the other two places where it is modified is via:
(src/srcs.c line 466) cat->v_skw[offp+i_r]+=vr;
(src/srcs.c line 571) cat->v_skw[offp+i_r]*=vg*factor_vel;

I would say that these two lines assume that the array is initialized to zero somewhere else, but I don't think this is the case... What do you say, @damonge ?

**Comment by fjaviersanchez** [comment]
Yes, they're initialized to zero with the line: `cat->v_skw=my_calloc(cat->nsrc*cat->nr,sizeof(float));`

**Comment by andreufont** [comment]
Ouch! I could have sworn that I read malloc instead of calloc... never mind :-)

**Comment by fjaviersanchez** [comment]
Redshift for the DLAs:

image

RSD term:

image

NHI:

image

It processes one file in 30 seconds. We can send all files as independent processes so this is still quite fast.

**Comment by andreufont** [comment]
About the plots: the last one, is it the cumulative distribution function, or an actual histogram of column densities? If it is the last one, we might have a bug, since we should have WAY MORE systems with log(N) = 20 than with log(N) = 22.

**Comment by fjaviersanchez** [comment]
It's the latter but I forgot that the file that I was using reads the cumulative distribution. My bad.

**Comment by fjaviersanchez** [comment]
Fixed:

image

**Comment by jfarr03** [comment]
@fjaviersanchez - could you make a plot of dn/dN directly from the Zheng file?

**Comment by fjaviersanchez** [comment]
@jfarr03 this is it :)

image

**Comment by fjaviersanchez** [comment]
And this is the cumulative:

image

**Comment by andreufont** [comment]
Hi @fjaviersanchez - First of all, appologies, I wrote the previous comment from James computer :-)

Looking at your plot, there has to be something funny. Your f(z,N) has to be always positive! It is afterall a probability...

**Comment by andreufont** [comment]
Thanks Javier!

@jfarr03, could you accept the pull request?

**Comment by jfarr03** [comment]
Done!

**Pull request merged**
