### PR TITLE
First attempt to use pyigm

### PR DESCRIPTION
**Pull request by fjaviersanchez**
This is my first attempt to use pyigm's functions to add DLAs. @jfarr03 could you please test it before merging?

Thanks!

### CODE REVIEW

**Comment by jfarr03** [comment]
Sorry I completely missed this! I'll test it now. 

I think in future, it would be good to work on the file 'DLA.py' rather than 'add_DLA.py' if that's possible? The former is slightly re-formatted version of the latter, which I adapted to fit in with the overall pipeline rather than as a standalone script (though I realise I forgot to actually mention this at all!)

**Comment by fjaviersanchez** [comment]
I’ll try to move it there then. Thanks!

**Comment by jfarr03** [comment]
No worries - I made a new branch igmhub/LyaCoLoRe called update_DLA which has the changes you made copied across to DLA.py. 

At the moment, it doesn't seem to be working for me: I'm currently getting an error "fN.model.eval: z=3.00025 not within self.zmnx=0.5,3". Looking into it, this seems to come from the default model having z=3 as some sort of maximum z value. I don't know if it's ok just to set this to something else?

**Comment by fjaviersanchez** [comment]
@jfarr03 I think this has an easy fix actually.

So after you do `fN_default = FNModel.default_model()` you can do `fN_default.zmnx=(0.5,4)` and that should work :)

**Comment by jfarr03** [comment]
Ok thanks - I'll give that a go and will get back to you!

**Comment by jfarr03** [comment]
That seems to have solved one problem, but there now seems to be a different problem: the value of N generated seem to be far too large (now they are of order 10**19, whereas before they were of order 10**-5). I guess this is something to do with the scaling in line 106 here? I can't quite see what's wrong with it but maybe I'm missing something obvious!

**Comment by andreufont** [comment]
Hi @fjaviersanchez - I took a better look at the code, and there are a couple of issues:
 - In general we would like code to be reproducible, i.e., we'd like to get the same DLAs if we redo the mock. To do that we need to pass a particular seed. This is done in the rest of LyaCoLoRe, in particular when adding extra power, but it is not done in DLA.py. We should pass a seed, or an instance of np.random.
 - As James mentioned, there are many orders of magnitude difference between the pyigm and the old version. I think this is due to problems with the units / normalization in the code with pyigm, since the old code gave reasonable results.
 - In the pyigm version of the code, the second time it is used it should be to generate random values for the column density of each DLA, i.e., equivalent to the old get_N function. However, the current pyigm version calls a function that just computes the mean density, and does not assign values of N_HI (or Ndla in the code). 

It would be good if you could take another look at the code, and compare the old and the new version. Alternatively, may be @Andrea-MG can take a look at it now that she is more familiar with LyaCoLoRe.

**Comment by fjaviersanchez** [comment]
@andreufont thanks for the suggestions! I'll add options to preset a random seed. Yes, I was taking a look at this yesterday and I think there's an issue with the units (when I convert from comoving density to density in `z` space I may have introduced some extra factors that aren't necessary here) I'll try to modify this asap.

**Comment by andreufont** [comment]
Great! This is not a show-stopper, so no need to prioritize it. But yes, it would be good to have the right DLAs for the next round of mocks (v3.0), that James might be able to generate in the next few days.

**Comment by fjaviersanchez** [comment]
@andreufont today I noticed that I was using the number of HI particles instead of the DLA density as N (that's why you see the 1e19 vs the 1e-5). I am fixing that now. Sorry it is taking forever.

**Comment by andreufont** [comment]
No worries. We will not have v3 until the end of the month, so it is not urgent.

**Comment by fjaviersanchez** [comment]
I think I got it to work. Could you please add me as a collaborator for the repo so I can push directly to the branch that @jfarr03 opened?

**Comment by fjaviersanchez** [comment]
I am closing this PR and opening a new one from the branch that James created.

**Pull request closed without merging**
