### PR TITLE
Update dla

### PR DESCRIPTION
**Pull request by fjaviersanchez**
I tested the functions separately and they seem to work but, @jfarr03 could you take a look and let me know if this works for you, please?

### CODE REVIEW

**Comment by andreufont** [comment]
Hi @fjaviersanchez - There are indentation errors. Note that now it is trivial to test the code yourself, by using small test data already in the repo. 

For instance, you can go to your base folder (in my case $HOME/Programs/igmhub/LyaCoLoRe) and run the following:

mkdir test-run

scripts/make_master.py --in-dir example_data/raw_colore_1000/ --out-dir test/ 

scripts/make_transmission.py --in-dir example_data/raw_colore_1000/ --out-dir test/ --pixels 0

These scripts run in a couple of seconds, and test the main pieces of the code.

**Comment by andreufont** [comment]
Hi @fjaviersanchez - I pushed a couple of changes, to allow users to pass the random seed to the DLA code. I also renamed the two "cosmo" objects that were cohabiting DLA.py. 

Finally, I added some comments on the code after out chat.

**Comment by fjaviersanchez** [comment]
@andreufont I changed the function `get_N` as you suggested and it seems to be working. The DLAs are put consistently in the position that they should, the values for logN change a bit (~0.1) from the old version to the one using `pyigm` but I guess this is expected. Please, feel free to check it out and let me know if you have any more comments/requests.

**Comment by andreufont** [comment]
@fjaviersanchez - the code was not really using the new pyigm code, it was calling the old cummulative function. I don't think the pyigm code is correct as it is now, since it calls evaluate (that returns f(N)) but treats it as if it was a cummulative function.

**Pull request merged**
