### PR TITLE
boot-up test

### PR DESCRIPTION
**Pull request by londumas**
boot-up test

### CODE REVIEW

**Comment by londumas** [comment]
@jfarr03, can you do a review, and then merge if it is ok. The branch has the very simple tests working.

**Comment by jfarr03** [comment]
@londumas Thanks for doing this. Can you clarify which tests this update includes?

Also, I might be doing something wrong, but something isn't working for me with the setup file. If I run 
make changes to, for example, `py/utils.py`, then run `python setup.py install --user`, the changes do not appear in subsequent uses of `utils`. I'm not sure why this is, but it seems to work ok with the old version. Any ideas why this might be?

**Comment by londumas** [comment]
@jfarr03,
 - I am doing a very simple test, which is can I open the requirements.txt file and are the required library installed.
 - I am trying to fix the issue you found, tell if it did the trick
 - the reason why I was not using files in `py/`, is that normally all python library should be in `py/LyaCoLoRe/`, not in `py`. but we can correct that later.

**Comment by londumas** [comment]
@jfarr03, could you try this branch again and see if I fixed the issue of files in `py`?

**Pull request closed without merging**
