### PR TITLE
Fixed generate_rnd on the low-z end

### PR DESCRIPTION
**Pull request by fjaviersanchez**
This PR addresses #21

### CODE REVIEW

**Comment by andreufont** [comment]
@jfarr03 - This request would add a dependency to desisim code. I'm not sure this is a bad thing, but it is possibly the first dependency to desi specific code, and we should consider whether we want to put it here or not. 

The alternative would be that in LyaCoLoRe we have a code that generates randoms for the full sky, but the right dn/dz, and then in desisim we have a short script (equivalent to quickquasars) that just applies the footprint.

Any thoughts?

**Comment by jfarr03** [comment]
I'm not sure either - would it seem odd if make_master/make_transmission return QSOs and spectra over the whole sky, but then the randoms produces them only over the DESI footprint? 

Maybe it could have a the capability to use only the DESI footprint, but I feel the option to avoid using DESI code would be nice too? Then it would be useful both for DESI analyses in the near future, but can also stand independently if needed.

**Comment by fjaviersanchez** [comment]
hmmm, what about creating a subfolder: `desi` where we put this version of the code and leave one agnostic?

**Comment by andreufont** [comment]
Sure, we could do that as well. Let's put anything that uses desihub modules in a separate folder, to distinguish it from the main code that should not be survey specific. Thanks!

**Pull request merged**
